"""
error code
"""
PARAM_ENTRY_101_ERROR = 101
VALIDATION_102_ERROR = 102
USERNAME_PASSWORD_103_ERROR = 103
OBS_ACCESS_104_ERROR = 104
AISHU_HUB_ACCESS_105_ERROR = 105
INVALID_USER_SESSION_106 = 106
INVALID_SERVER_SIGNATURE_107 = 107
AUTH_108_ERROR = 108
DATA_NOT_FOUND_109 = 109
DATA_ALREADY_MODIFIED_110 = 110
DATA_ALREADY_EXIST_111 = 111
INTERNAL_SERVER_112_ERROR = 112
DATA_INTEGRATION_113_ERROR = 113
DATA_UPDATE_114_ERROR = 114
ADMIN_USER_115_ERROR = 115

"""
error message
"""

PARAM_ENTRY_101_ERROR_MESSAGE = "necessary parameter is not entered"
VALIDATION_102_ERROR_MESSAGE = "parameters are invalid"
USERNAME_PASSWORD_103_ERROR_MESSAGE = "The username or password is incorrect"
OBS_ACCESS_104_ERROR_MESSAGE = "OBS access error"
AISHU_HUB_ACCESS_105_MESSAGE = "AISHU HUB access error"
INVALID_USER_SESSION_106_MESSAGE = "access_token is invalid"
INVALID_SERVER_SIGNATURE_107_MESSAGE = "invalid client_id or client_secret"
AUTH_108_ERROR_MESSAGE = "Forbidden"
DATA_NOT_FOUND_109_MESSAGE = "Data Not Found"
DATA_ALREADY_MODIFIED_110_MESSAGE = "Data Already Modified"
DATA_ALREADY_EXIST_111_MESSAGE = "Data Already Exist"
INTERNAL_SERVER_112_ERROR_MESSAGE = "Internal server error"
DATA_INTEGRATION_113_ERROR_MESSAGE = "Data integration error"
DATA_UPDATE_114_ERROR_MESSAGE = "Update action was not excuted"
ADMIN_USER_115_ERROR_MESSAGE = "Admin user not exsit"
